# Generated by Django 4.1.6 on 2023-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
