# Generated by Django 4.1.6 on 2023-02-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartitems_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
